// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function buildDatabaseUrl() {
  const direct = process.env["DATABASE_URL"];
  if (direct?.trim()) return direct;

  const user = process.env["DB_USER"] || "";
  const password = process.env["DB_PASSWORD"] || "";
  const host = process.env["DB_HOST"] || "";
  const port = process.env["DB_PORT"] || "3306";
  const database = process.env["DB_NAME"] || "";

  if (!user || !password || !host || !database) return undefined;

  const encodedPassword = encodeURIComponent(password);
  return `mysql://${user}:${encodedPassword}@${host}:${port}/${database}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
